import { DeliveryPlatforms, GetOrdersRequest, OrderStatus } from "./types";

export const ordersMock: GetOrdersRequest = {
  orders: [
    {
      id: `4561`,
      deliveryMan: `Gabriel`,
      clientName: `João`,
      platform: DeliveryPlatforms.IFOOD,
      status: OrderStatus.REQUESTED,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      id: `2867`,
      deliveryMan: `Guilherme`,
      clientName: `Gabriel`,
      platform: DeliveryPlatforms.NINENINE_FOOD,
      status: OrderStatus.SENT,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      id: `22378`,
      deliveryMan: `João`,
      clientName: `Pedro`,
      platform: DeliveryPlatforms.NINENINE_FOOD,
      status: OrderStatus.SENT,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      id: `7827`,
      deliveryMan: `Pedro`,
      clientName: `João`,
      platform: DeliveryPlatforms.NINENINE_FOOD,
      status: OrderStatus.SENT,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      id: `78532`,
      deliveryMan: `Rafael`,
      clientName: `João`,
      platform: DeliveryPlatforms.NINENINE_FOOD,
      status: OrderStatus.SENT,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    {
      id: `75382`,
      deliveryMan: `Gustavo`,
      clientName: `Saraiva`,
      platform: DeliveryPlatforms.NINENINE_FOOD,
      status: OrderStatus.SENT,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  ],
};
